djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.contrib.auth.views import LogoutView

app_name = "mainapp"
urlpatterns = [
    path('', views.render_index, name='index'),
    path('announcement/<int:id>/', views.render_announcement, name='announcement'),
    path('profile/<int:id>/', views.render_profile, name='profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('reg/', views.RegistrationView.as_view(), name='reg'),
    path('add/', views.AnnouncementCreateView.as_view(), name='add'),
    path('<slug:pk>/edit/', views.AnnouncementUpdateView.as_view(), name='update'),
    path('<slug:pk>/remove/', views.AnnouncementDeleteView.as_view(), name='delete'),
    path('<slug:pk>/edit_info/', views.UserUpdateView.as_view(), name='info_update'),
    path('<slug:pk>/remove_info/', views.UserDeleteView.as_view(), name='info_delete')
]

praktika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>avido</title>
</head>
<body>
    <div class="container">
        <div class="add">
            <a class="btn btn-outline-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'mainapp:index' %}" role="button">Главная страница</a>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-danger" value="Сохранить">
            </form>
        </div>
    </div>
</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Avido</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand">Объявления</div>
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class='col d-flex justify-content-around' aria-current="page" href="{% url 'mainapp:profile' request.user.id %}">Личный кабинет</a>
                </li>
                <li class="nav-item">
                    <a class='col d-flex justify-content-around' aria-current="page" href="{% url 'mainapp:logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class='col d-flex justify-content-around' aria-current="page" href="{% url 'mainapp:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class='col d-flex justify-content-around' aria-current="page" href="{% url 'mainapp:reg' %}">Зарегистрироваться</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="row align-items-start">
        {% for i in announcement %}
            <div class="col" style="padding-top: 35px">
                <div class="card" style="width: 18rem;">
                    <div class="card-header" style="text-align: center">{{ i.name_ad }}<br></div>
                    <div class="card-body">
                        <img src="{{ i.image.url }}" style="width:150px; display: block; margin: auto" alt="picture"><br>
                        <p class="card-text">Стоимость: {{ i.price }}</p>
                        <p class="card-text">Город: {{ i.city }}</p>
                        <p class="card-text">Дата публикации: {{ i.date_pub }}</p>
                        <p class="card-text">Количество просмотров: {{ i.number_views }}</p>
                        <a href="{% url 'mainapp:announcement' i.id %}" class="btn btn-outline-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div><br>
</div>
</body>
</html>

templates/inform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Объявление {{announcement.id }}</title>
</head>
<body>
    <div class="container">
        <div class="about">
            <div class="announcements">
                <div class="alert alert-success" role="alert">
                    <b>Название объявления: </b> {{ announcement.name_ad }}<br><br>
                    <b>Категория: </b> {{ announcement.category }}<br>
                    <b>Город: </b> {{ announcement.city }}<br>
                    <b>Описание объявления: </b> {{ announcement.description_ad }}<br>
                    <b>Дата публикации: </b> {{ announcement.date_pub }}<br>
                    <b>Стоимость: </b> {{ announcement.price }}<br>
                    <b>Пользователь: </b> {{ announcement.user }}<br>
                    <b>Количество просмотров: </b> {{ announcement.number_views }}<br>
                    <b>Статус: </b> {{ announcement.status_ad }}<br>
                </div>
            </div>
            <div class="seller">
                <div class="alert alert-success" role="alert">
                    <b>Продавец: </b> {{ seller.username }}<br>
                    <b>Имя: </b> {{ seller.first_name }}<br>
                    <b>Фамилия: </b> {{ seller.last_name }}<br>
                    <b>Отчество: </b> {{ seller.patronymic }}<br>
                    <b>Адрес электронной почты: </b> {{ seller.email }}<br>
                    <b>Номер телефона: </b> {{ seller.phone }}<br>
                    <b>Когда удобно принимать звонки: </b> {{ seller.convenient_time }}<br><br>
                    <a href="#" class="btn btn-success">Связаться с продавцом</a><br>
                    <a class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'mainapp:index' %}" role="button">Главная</a><br>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/login.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Авторизация</title>
</head>
<body>
    <div class="container">
        <h1>Авторизация:</h1>
        <div class="add">
            <a class="btn btn-outline-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'mainapp:index' %}" role="button">Назад</a>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <input type="submit" class="btn btn-outline-success" value="Войти">
                <br><br>
                <p>Если у вас нет аккаунта, то вы можете <a href="{% url 'mainapp:reg' %}" role="button">Зарегистрироваться</a></p>
            </form>
        </div>
    </div>
</body>
</html>

templates/profile.html
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Личный кабинет</title>
</head>
<body>
<div class="container">
    <div class="about">
        <div class="seller">
            <div class="alert alert-success" role="alert">
                <b>Имя: </b> {{ seller.first_name }}<br>
                <b>Фамилия: </b> {{ seller.last_name }}<br>
                <b>Адрес электронной почты: </b> {{ seller.email }}<br>
                <b>Номер телефона: </b> {{ seller.phone }}<br>
                <b>Когда удобно принимать звонки: </b> {{ seller.convenient_time }}<br><br>
                <a class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'mainapp:index' %}" role="button">Главная</a><br>
                <a class="btn btn-warning" href="{% url 'mainapp:info_update' seller.id %}" role="button" style="margin-bottom: 20px">Изменить данные</a>
                <a class="btn btn-warning" href="{% url 'mainapp:info_delete' seller.id %}" role="button" style="margin-bottom: 20px">Удалить данные</a>
            </div>
        </div>
        {% if request.user.is_superuser or request.user|has_group:"Администратор" or request.user|has_group:"Модератор" %}
        <div class="row align-items-start">
            {% for i in announcement %}
                <div class="col" style="padding-top: 35px">
                    <div class="card" style="width: 18rem;">
                        <div class="card-header" style="text-align: center">{{ i.name_ad }}<br></div>
                        <div class="card-body">
                            <p class="card-text">Стоимость: {{ i.price }}</p>
                            <p class="card-text">Город: {{ i.city }}</p>
                            <p class="card-text">Дата публикации: {{ i.date_pub }}</p>
                            <p class="card-text">Количество просмотров: {{ i.number_views }}</p>
                            <a href="{% url 'mainapp:announcement' i.id %}" class="btn btn-outline-primary">Подробнее</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div><br>
        <h1>Модерации объявлений</h1>
        <div class="time-work">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Дата модерации</th>
                  <th scope="col">Оъявление</th>
                  <th scope="col">Модератор</th>
                  <th scope="col">Публикация</th>
                  <th scope="col">Причина отклонения</th>
                </tr>
              </thead>
              <tbody>
                  {% for i in moderation %}
                      <tr>
                      <th scope="row">{{ i.date_moder }}</th>
                          <td>{{ i.ad }}</td>
                          <td>{{ i.user }}</td>
                          <td>{{ i.publication }}</td>
                          <td>{{ i.reason }}</td>
                      </tr>
                  {% endfor %}
              </tbody>
            </table>
        </div>
        {% endif %}
        {% if request.user.is_superuser or request.user|has_group:"Администратор" %}
            <h1>Категории</h1>
            <div class="time-work">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Название категории</th>
                      <th scope="col">Код</th>
                      <th scope="col">Родительская категория</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for i in category %}
                          <tr>
                          <th scope="row">{{ i.name_cat }}</th>
                              <td>{{ i.code }}</td>
                              <td>{{ i.parent }}</td>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
            </div>
            <h1>Города</h1>
            <div class="time-work">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Название города</th>
                      <th scope="col">Регион</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for i in cities %}
                          <tr>
                          <th scope="row">{{ i.name_city }}</th>
                              <td>{{ i.region }}</td>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
            </div>
            <h1>Регионы</h1>
            <div class="time-work">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Название региона</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for i in region %}
                          <tr>
                          <th scope="row">{{ i.name_reg }}</th>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
            </div>
        {% endif %}
        {% if request.user|has_group:"Пользователь" %}
            <a class="btn btn-outline-success" href="{% url 'mainapp:add'%}" role="button">Создать новое объявление</a>
            <div class="row align-items-start">
                {% for i in announcement_user %}
                    <div class="col" style="padding-top: 35px">
                        <div class="card" style="width: 18rem;">
                            <div class="card-header" style="text-align: center">{{ i.name_ad }}<br></div>
                            <div class="card-body">
                                <p class="card-text">Стоимость: {{ i.price }}</p>
                                <p class="card-text">Город: {{ i.city }}</p>
                                <p class="card-text">Дата публикации: {{ i.date_pub }}</p>
                                <p class="card-text">Количество просмотров: {{ i.number_views }}</p>
                                <a href="{% url 'mainapp:announcement' i.id %}" class="btn btn-outline-primary" style="margin-bottom: 20px">Подробнее</a>
                                <a class="btn btn-outline-warning" href="{% url 'mainapp:update' i.id %}" role="button" style="margin-bottom: 20px">Изменить объявление</a>
                                <a class="btn btn-outline-danger" href="{% url 'mainapp:delete' i.id %}" role="button" style="margin-bottom: 20px">Удалить объявление</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div><br>
        {% endif %}
    </div>
</div>
</body>
</html>

templates/registration.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Регистрация</title>
</head>
<body>
    <div class="container">
        <h1>Регистрация:</h1>
        <div class="add">
            <a class="btn btn-outline-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'mainapp:index' %}" role="button">Назад</a>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <input type="submit" class="btn btn-outline-success" value="Зарегистрироваться">
            </form>
        </div>
    </div>
    <br>
</body>
</html>